from scipy.stats import poisson
import unittest
from math import exp
from typing import Callable, Dict


def sample_tvd(sample_data: Dict[int, int], pmf: Callable[[int], float]):
    """Given a probability mass function F and sample data with sample mass function F', returns
    sup_x (F'(x) - F(x)). Assumes that F(x) = 0 for all x < 0."""
    remaining_mass = 1.0
    maximum_distance = 0.0
    number_of_samples = sum(sample_data.values())

    i = 0
    while remaining_mass > maximum_distance:
        sample_pmf = sample_data[i] / number_of_samples if i in sample_data else 0.0
        distance = abs(pmf(i) - sample_pmf)
        if distance > maximum_distance:
            maximum_distance = distance
        remaining_mass -= pmf(i)
        i += 1

    return maximum_distance


def dkw_p_value(sample_data: Dict[int, int], pmf: Callable[[int], float], tvd_bound: float):
    """Statistical test based on the DKW inequality ("The Tight Constant in the Dvoretzky-Kiefer-Wolfowitz
    Inequality" by P. Massart, Annals of Probability 18(3), 1990.) The null hypothesis is that sample_data is drawn
    from a distribution with total variation distance at least tvd_bound away from the distribution of pmf. This
    function returns an upper bound on the p-value subject to the assumption that elements of sample_data are drawn
    independently. The intended use is that the sample_data is generated by repeatedly running a function that should
    generate i.i.d. samples from pmf's distribution; thus the null hypothesis is that the sample-generating code
    breaks resulting in a distribution at least tvd_bound total variation distance away from the intended one,
    and we wish to reject it."""
    n = sum(sample_data.values())
    sample_distance_from_pmf = sample_tvd(sample_data=sample_data, pmf=pmf)

    """If the sample itself is further than tvd_bound from the target distribution, then we're clearly not going to get 
    anything of value so just return an upper bound of 1."""
    if tvd_bound < sample_distance_from_pmf:
        return 1.0

    """Write the sample data's true pmf as F', write its sample pmf as \hat{F'}, and write the given pmf be F. Then 
    by the triangle inequality, d_TV(\hat{F'}, F') >= d_TV(F, F') - d_TV(\hat{F}, F), so the following is a lower bound 
    on d_TV(\hat{F'}, F') under the null hypothesis."""
    null_sample_generator_from_pmf_bound = tvd_bound - sample_distance_from_pmf

    """The DKW inequality says that for any lambda > 0: Pr(\sqrt{n} * d_TV(\hat{F'}, F') > lambda) <=  
    2e^(-2*lambda^2). Reparameterising lambda to \sqrt{n} * nu gives Pr(d_TV(\hat{F'}, F') > nu) <= 
    2e^(-2*n*nu^2). So under the null hypothesis, the following is an upper bound on the probability of \hat{F'} 
    being at least as close to F under d_TV as it is."""
    return min(1.0, 2.0 * exp(-2.0 * n * (null_sample_generator_from_pmf_bound ** 2)))


class TestDKW(unittest.TestCase):
    def testCoin(self):
        def coin_pmf(k):
            if k in [0, 1]:
                return 0.5
            return 0
        sample_data = {0: 5, 1: 5}
        self.assertEqual(0., sample_tvd(sample_data=sample_data, pmf=coin_pmf))
        # LHS here is roughly .573001.
        self.assertEqual(2.*exp(-20. * (0.25 ** 2)), dkw_p_value(sample_data=sample_data, pmf=coin_pmf, tvd_bound=0.25))

        sample_data = {0: 50, 1: 50}
        self.assertEqual(0., sample_tvd(sample_data=sample_data, pmf=coin_pmf))
        # LHS here is roughly .002222.
        self.assertEqual(2. * exp(-200. / 16.), dkw_p_value(sample_data=sample_data, pmf=coin_pmf, tvd_bound=0.25))

    def testDie(self):
        def die_pmf(k):
            if 1 <= k <= 6:
                return 1./6.
            return 0
        sample_data = {1: 20, 2: 20, 3: 20, 4: 20, 5: 20}
        self.assertEqual(1./6., sample_tvd(sample_data=sample_data, pmf=die_pmf))
        self.assertEqual(1., dkw_p_value(sample_data=sample_data, pmf=die_pmf, tvd_bound=.2))

        # Total 100 entries.
        sample_data = {1: 15, 2: 18, 3: 16, 4: 13, 5: 20, 6: 18}
        # LHS here is 11/300.
        self.assertEqual(1./6. - .13, sample_tvd(sample_data=sample_data, pmf=die_pmf))
        # LHS here is roughly 0.0096347
        self.assertAlmostEqual(2. * exp(-200. * (.2 - 11./300.) ** 2),
                               dkw_p_value(sample_data=sample_data, pmf=die_pmf, tvd_bound=.2),
                               delta=0.0000000000000001)

    def testPoisson(self):
        pmf = lambda k: poisson.pmf(k=k, mu=1)
        sample_data = {0: 1}
        self.assertEqual(1.-exp(-1.), sample_tvd(sample_data=sample_data, pmf=pmf))

        sample_data = {0: 50, 1: 0, 2: 25}
        self.assertEqual(exp(-1.), sample_tvd(sample_data=sample_data, pmf=pmf))


if __name__ == '__main__':
    unittest.main()
